### ISSUE TITLE
빨리 업데이트 해주세요

### ISSUE THREAD

**Issue by wonjinYi** [Last-SilverLight-End/ShowMeTheHomepage#1]
![image](https://user-images.githubusercontent.com/25413566/188835923-8740f052-9a8c-4f58-91ec-3a992f78fdb4.png)

업데이트해주세요
앞으로는 하루에 10커밋 부탁드립니다.

**Comment by Last-SilverLight-End** [comment]
main update 했습니다 gh-pages branch 는 수시로 업데이트 되니 참고 바래요 아마 추석때는 계속해서 업데이트 될듯 하네요
